Release `v4.0.0-alpha.1`
paritytech/ink pull request #1363
Opened 2022-08-23 19:46 UTC by HCastano

Two main reasons I want to get this out.

1. It's the beginning of some changes related to the metadata, and we need an ink!
   release in order to make `cargo-contract` releases which can understand this.
2. Green's storage PR is going to get merged soon, and I'd prefer if that was in a
   standalone release.

2022-08-23 20:15 UTC, HCastano commented
Hmm, will look into CI failures tomorrow 🕵️

2022-08-24 11:29 UTC, cmichi commented on CHANGELOG.md
> +- :x: Add Mapping::contains(key) and Mapping::insert_return_size(key, val) ‒ [#1224](https://github.com/paritytech/ink/pull/1224)
```suggestion
- :x: Add `Mapping::contains(key)` and `Mapping::insert_return_size(key, val)` ‒ [#1224](https://github.com/paritytech/ink/pull/1224)
```

2022-08-24 11:35 UTC, cmichi requested changes

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +- :x: Add `version` field to ink! metadata - [#1313](https://github.com/paritytech/ink/pull/1313)
```suggestion
- :x: Add `Mapping::contains(key)` and `Mapping::insert_return_size(key, val)` ‒ [#1224](https://github.com/paritytech/ink/pull/1224)
- Add [`payment-channel`](https://github.com/paritytech/ink/tree/master/examples/payment-channel) example ‒ [#1248](https://github.com/paritytech/ink/pull/1248)
- :x: Add `version` field to ink! metadata ‒ [#1313](https://github.com/paritytech/ink/pull/1313)
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +# Version 4.0.0-alpha.1
```suggestion
## Version 4.0.0-alpha.1
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +## Breaking Changes
```suggestion
### Breaking Changes
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +## Added
```suggestion
### Added
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +## Changed
```suggestion
### Changed
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +## Removed
```suggestion
### Removed
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +## Compatibility
```suggestion
### Compatibility
```

2022-08-24 11:35 UTC, cmichi commented on CHANGELOG.md
> +compatibility was restored in `v3.3.0`.
Could you add something on how to migrate and what the implications are? So along the lines of https://github.com/paritytech/ink/blob/master/CHANGELOG.md#breaking-changes.

2022-08-24 16:53 UTC, cmichi commented on CHANGELOG.md
> +- :x: Add `version` field to ink! metadata - [#1313](https://github.com/paritytech/ink/pull/1313)
```suggestion
- Add [`payment-channel`](https://github.com/paritytech/ink/tree/master/examples/payment-channel) example ‒ [#1248](https://github.com/paritytech/ink/pull/1248)
- :x: Add `version` field to ink! metadata ‒ [#1313](https://github.com/paritytech/ink/pull/1313)
```

![screenshot-github com-2022 08 24-18_52_01](https://user-images.githubusercontent.com/241530/186477331-f92d4746-a0ca-4fd5-ab2e-a0b5cffa656e.png)

2022-08-24 16:54 UTC, cmichi commented on CHANGELOG.md
> +- Move linting into ink repo - [#1361](https://github.com/paritytech/ink/pull/1267)
```suggestion
- Move ink! linter into `ink` repository ‒ [#1361](https://github.com/paritytech/ink/pull/1267)
```

2022-08-24 16:55 UTC, cmichi commented on CHANGELOG.md
> +### Compatibility
Can you make the compatibility section the first section under `## Version 4.0.0-alpha.1`? Then it'll be consistent with the other releases.

2022-08-24 17:47 UTC, cmichi approved these changes
Thank you! 🙏

2022-08-24 18:31 UTC, HCastano commented
The ink-waterfall failure is related to some of the metadata changes that I want to address by publishing this release, so I'm gonna merge this anyways.

2022-08-24 18:32 UTC, merged