Trim docs in events specification
paritytech/ink pull request #1459
Opened 2022-10-31 17:46 UTC by TomaszWaszczyk

This PR closes: https://github.com/paritytech/ink/issues/1448

2022-11-01 08:53 UTC, SkymanOne approved these changes

2022-11-01 09:00 UTC, ascjones reviewed
Please add a simple test for this, should be able to base it on one of the existing ones e.g the one from #1385 

https://github.com/paritytech/ink/blob/7ddf87f4294d09cbb023ce2df35e40376a912e18/crates/metadata/src/tests.rs#L213

2022-11-01 09:40 UTC, SkymanOne commented
I see that CI fails. Can you please merge master head into your branch?

2022-11-07 08:54 UTC, SkymanOne requested changes
Looks good so far, please merge master into your branch and make sure CI passes :)

2022-11-07 08:54 UTC, SkymanOne commented on crates/metadata/src/tests.rs
> +                " Example",
Why add a whitespace here?

2022-11-07 08:56 UTC, ascjones commented on crates/metadata/src/tests.rs
> +fn trim_events_in_specification() {
This doesn't actually test the event docs, it is testing `ConstructorSpecBuilder::docs`

2022-11-07 08:56 UTC, ascjones commented on crates/metadata/src/tests.rs
> +    let deserialized: ConstructorSpec<PortableForm> =
Should be testing the `EventSpecBuilder` and `EventParamSpecBuilder` which you have changed.

2023-02-23 22:54 UTC, HCastano commented
@TomaszWaszczyk or @SkymanOne do either one of you want to finish this up, or should we close this?

2023-02-23 22:55 UTC, closed without merging

2023-02-23 23:12 UTC, TomaszWaszczyk commented
I will back here when ready.