`[ink_e2e]` spawn a separate contracts node instance per test
paritytech/ink pull request #1642
Opened 2023-02-03 16:52 UTC by ascjones

Currently the E2E tests depend on a shared instance of `substrate-contracts-node` running in the background. This can cause issues where tests are not independent, and can be non deterministic when different tests share account ids. See https://github.com/paritytech/ink/pull/1615.

This PR spawns a unique instance of `substrate-contracts-node` per test, so the tests are completely isolated. I have copied the [TestNodeProcess](https://github.com/paritytech/subxt/blob/master/testing/integration-tests/src/utils/node_proc.rs) from `subxt` in order to manage the spawning of the node process and retrieving the unique ports which allow them to run in parallel. This also ensures that the processes are killed on drop.

The default is assuming `substrate-contracts-node` is installed on the PATH. The alternative is to specify the `CONTRACTS_NODE` env variable.

2023-02-04 13:18 UTC, SkymanOne approved these changes

2023-02-04 13:18 UTC, SkymanOne commented on crates/e2e/src/tests.rs
> -#[tokio::test]
Maybe worth replacing this with a test on launching the test node

2023-02-04 13:22 UTC, SkymanOne requested changes
Can you please add CHANGELOG entry?

2023-02-07 10:48 UTC, SkymanOne approved these changes
LGTM!

2023-02-07 11:34 UTC, cmichi approved these changes
Thanks, it's good!

2023-02-07 11:43 UTC, merged