Linter: Warn when number primitive is annotated with `#[ink(topic)]`
paritytech/ink pull request #1837
Opened 2023-07-05 07:53 UTC by jubnzv

Closes #1436

2023-08-09 22:12 UTC, SkymanOne requested changes
Overall, looks very good. We just need to decide whether to merge it as a minor patch of the ink! 4, or make it compatible with Events 2.0 and merge it in ink! 5.

I personally think we should make it work with Event 2.0 as ink! 5.0 might be released soon, and we will still have to add support for the new event definition.

2023-08-09 22:12 UTC, SkymanOne commented on linting/src/primitive_topic.rs
> +// Copyright 2018-2023 Parity Technologies (UK) Ltd.
```suggestion
// Copyright (C) Parity Technologies (UK) Ltd.
```

2023-08-09 22:12 UTC, SkymanOne commented on linting/src/primitive_topic.rs
> +    /// **Known problems:** Events 2.0 currently are not supported:
If events are not supported then we should either merge this PR into `4.2` branch or make it compatible with the Events 2.0

2023-08-09 22:12 UTC, SkymanOne commented on linting/src/primitive_topic.rs
> +/// Returns `true` if `ty` is a primitive type that should not be annotated with
```suggestion
/// Returns `true` if `ty` is a numerical primitive type that should not be annotated with
```

2023-08-09 22:12 UTC, SkymanOne commented on linting/src/primitive_topic.rs
> +/// Reports field of the event structure
```suggestion
/// Reports a topic-annotated field with a numerical primitive type
```

2023-08-09 22:15 UTC, SkymanOne commented on linting/src/primitive_topic.rs
> +    /// **Known problems:** Events 2.0 currently are not supported:
My bad, it looks like your recent commit: https://github.com/paritytech/ink/pull/1837/commits/f10985bd17393a43f48468be305fd9801a1e1696 added the support for the Events 2.0. If that's the case, can you please update the comment?

2023-08-11 07:46 UTC, jubnzv commented
@SkymanOne Thanks for the review. I commited all the suggestions.

2023-08-11 12:20 UTC, SkymanOne requested changes
Tried to run the tests locally I got a bunch of compilation errors related to `clippy_utils`. 
 
The requested changes are what helped me to resolve the issue.

2023-08-14 12:43 UTC, jubnzv commented on linting/Cargo.toml
Done.

I updated `clippy_utils` version to `1d334696587ac22b3a9e651e7ac684ac9e0697b2` and set channel to `nightly-2023-07-14` in `rust-toolchain.toml`. `nightly-2023-07-14` is required, since this version [is used](https://github.com/rust-lang/rust-clippy/blob/1d334696587ac22b3a9e651e7ac684ac9e0697b2/rust-toolchain#L2) in `rust-clippy` at commit `1d334696587ac22b3a9e651e7ac684ac9e0697b2`.

How should we choose the `clippy` version for `linting`? Should we always take the latest version from the `clippy` `master` branch?

2023-08-14 13:25 UTC, SkymanOne commented on linting/Cargo.toml
Not sure what you mean by `clippy` here. If you are referring to `clippy_utils`, I've been following a template https://github.com/trailofbits/dylint/blob/v2.1.12/internal/template/Cargo.toml~ in dylint repo

2023-08-14 13:27 UTC, SkymanOne requested changes

2023-08-14 13:27 UTC, SkymanOne commented on linting/Cargo.toml
> +clippy_utils = { path = "/home/georgiy/Sources/rust-clippy/clippy_utils" }
This points to your home directory instead of the correct commit

2023-08-14 15:31 UTC, SkymanOne commented on linting/Cargo.toml
AFAIK we only have `rust-toolchain.toml` for the lining crate

2023-08-15 06:54 UTC, merged