fix: improve link to chats
paritytech/ink pull request #571
Opened 2020-11-07 21:43 UTC by TomaszWaszczyk

I wanted to join Element and Discord chats and saw that the links does not work.

Small fix.

2020-11-08 02:41 UTC, cmichi commented
@TomaszWaszczyk Thanks for the PR, but for me both links work? What are the errors you get? Do both not work for you?

2020-11-08 08:48 UTC, TomaszWaszczyk commented
Look at left bottom corner:
[ink.zip](https://github.com/paritytech/ink/files/5506037/ink.zip)

2020-11-09 06:15 UTC, cmichi commented on README.md
> +Talk to us on [Element](https://app.element.io/#/room/!tYUCYdSvSYPMjWNDDD:matrix.parity.io) or [Discord](https://discord.gg/ztCASQE)
```suggestion
Talk to us on [Element]([k2]) or [Discord]([l2])
```

The variables for those links already exist in the readme.

2020-11-09 06:17 UTC, cmichi requested changes
Ah now I got you, thanks for the Gif! The chats are linked two times in the Readme, once as images in the badges and once in the text. I was only looking at the badges.

2020-11-10 08:56 UTC, cmichi approved these changes

2020-11-10 09:45 UTC, cmichi commented on README.md
> +Talk to us on [Element]([k2]) or [Discord]([l2])
```suggestion
Talk to us on [Element][k2] or [Discord][l2]
```

2020-11-10 09:47 UTC, merged