Make contract docs visible to rustdoc
paritytech/ink pull request #616
Opened 2020-12-15 11:10 UTC by cmichi

Closes #336.
 
I need to make some of our example `mod` public, otherwise there will never be any documentation for the `pub`'s in that module. We should also think about if we want to change the `cargo contract new` template and the workshops.

In terms of how it currently looks I uploaded the output of `cargo doc --no-deps` for two examples:

* [flipper](http://tmp.creal.de/flipper-doc/flipper/index.html)
* [trait-erc20](http://tmp.creal.de/trait-erc20-doc/erc20/index.html)

I expect that we will need to discuss further details of what we want to hide/show in these docs, I created this PR also with the intention of starting this discussion and not with the idea of providing a perfect solution from the start.

2020-12-15 11:37 UTC, Robbepop commented
Actually this is only part of the solution. We also (finally) need dedicated `#[cfg(doc)]` aware ink! codegen that produces code specially for generating documentation using `cargo doc`.

2020-12-15 11:53 UTC, cmichi commented
>Actually this is only part of the solution. We also (finally) need dedicated #[cfg(doc)] aware ink! codegen that produces code specially for generating documentation using cargo doc. E.g. ink! will produce different output if it notices that it is compiling for cargo doc.

@Robbepop Did you take a look at the code?  That's exactly what I do e.g. [here](https://github.com/paritytech/ink/pull/616/files#diff-517dd12d245ab4f2f1cdfa3a94f8ef7b71dabd3a2833b94c7247f4eecd75730cR63-R70).

2021-01-12 14:11 UTC, Robbepop requested changes
The direction of this PR to solve the underlying issue is to implicitly expose the API of the smart contract to the outside thus enforcing `pub` ink! module.
Unfortunately this forces smart contract authors to have this constraint of a `pub` module.
What I'd like to see instead is to let the users decide what items and definitions they want to expose as with a normal Rust library or application and instead produce very clean and simple contract code with proper documentation everywhere when `#[cfg(doc)]` is enabled.
This requires yet another complete codegen for this case next to `ink-as-dependency` and `std` in the context of metadata and testing.

2021-01-14 13:31 UTC, cmichi commented
Closed in favor of #632 as a follow-up.

2021-01-14 13:31 UTC, closed without merging